version: "3"
services:
  miao-yunzai:
    container_name: miao-yunzai
    image: olivercwy/miao-yunzai:slim-latest
    # build:
    #   context: .
    restart: always
    ports:
      - "50831:50831"                                                 # 锅巴插件
    volumes:
      - ./app/home:/home/yunzai:z
    depends_on:
      redis: { condition: service_healthy }
    stdin_open: true
    tty: true
    user: "${DOCKER_USER}"

  redis:
    container_name: miao-redis
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: always
    volumes:
      - ./app/database:/data:z
    ulimits:
      memlock: -1
    user: "${DOCKER_USER}"
