name: Build & Publish Docker image

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: olivercwy/miao-yunzai

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: "Build and push Docker image: slim"
        uses: docker/build-push-action@v2
        with:
          context: ./docker-slim
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: olivercwy/miao-yunzai:slim-${{ steps.date.outputs.date }},olivercwy/miao-yunzai:slim-latest
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: "Build and push Docker image: full"
        uses: docker/build-push-action@v2
        with:
          context: ./docker-full
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: olivercwy/miao-yunzai:${{ steps.date.outputs.date }},olivercwy/miao-yunzai:latest,
          labels: ${{ steps.meta.outputs.labels }}

      - uses: gautamkrishnar/keepalive-workflow@v1